version: "3.9"  # optional since v1.27.0
services:
  influx:
    image: influxdb:2.0.8-alpine
    volumes:
    - ./devops/data/staging/influxdb:/var/lib/influxdb
    environment:
    - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
    - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
    - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG} 
    - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
    ports:
    - 8086:8086
    restart: unless-stopped
  mongo:
    image: mongo:4.4.9
    volumes:
    - ./devops/data/staging/mongo/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
  frontend:
    build: ../VueFrontendWebApp
    ports:
    - 8080:80
  # proxy:
  #   image: nginx
  #   volumes:
  #   - /devops/deployment/staging/nginx.conf:/etc/nginx/nginx.conf:ro
  #   links:
  #   - frontend
  #   ports:
  #   - 80:80
  backend: 
    build: ../backend
    ports:
    - 3000:3000
  ttn:
    build: ../ttn-listener
    environment:
    - MQTT_USERNAME=${MQTT_USERNAME}
    - MQTT_PASSWORD=${MQTT_PASSWORD}
    - BROKER_ADDRESS=${BROKER_ADDRESS}
    - BACKEND_BASE_URL=${BACKEND_BASE_URL}
    - BACKEND_PORT=${BACKEND_PORT}
  grafana:
    image: grafana/grafana:latest
    ports:
    - 4000:3000
    links:
    - influx

